name: Dart CI

# This workflow is triggered on pull requests and pushes to the repository.
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    name: Build, format, analyze and test the package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get

      # Consider passing '--output=none' to 'format' for no standard output.
      - name: Verify formatting
        run: dart format --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: Install coverage tools
        run: dart pub global activate coverage

      - name: Test with coverage
        run: dart pub global run coverage:test_with_coverage

      - name: Code Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          fail_ci_if_error: true
